module.exports = {
  apps: [
    {
      name: 'atenmed',
      script: 'server.js',
      instances: 1,
      exec_mode: 'fork',
      env_file: '.env',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_file: './logs/combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
      max_memory_restart: '500M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      wait_ready: false,
      listen_timeout: 10000,
      kill_timeout: 5000,
      shutdown_with_message: true,
      autorestart: true,
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'backups', '.git'],
      merge_logs: true,
      node_args: '--max_old_space_size=512',
    },
  ],
};
